name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  metrics:
    name: 'Update SVGs for Readme stats'
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.24
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: markdown
          filename: README.md
          markdown: TEMPLATE.md
          markdown_cache: '.github/svg_cache'
          
          base: ""
          
          config_octicon: yes
          
          plugin_stargazers: yes
          plugin_contributors: yes
