name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  metrics:
    name: 'Update SVGs for Readme stats'
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.24
        with:
          filename:  metrics.plugin.stargazers.svg
          plugin_stargazers_charts_type: chartist
          token: ${{ secrets.METRICS_TOKEN }}
          
 
          
          base: ""
          
          config_octicon: yes
          
          plugin_stargazers: yes
          plugin_contributors: yes

      - uses: lowlighter/metrics@v3.24
        with:
          filename:  metrics.plugin.contributors.svg
          token: ${{ secrets.METRICS_TOKEN }}
          
 
          
          base: ""
          
          config_octicon: yes
      
 
          plugin_contributors: yes
