name: 'Update SVGs for Readme stats'

on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

jobs:
  metrics:
    name: 'Update SVGs for Readme stats'
    runs-on: ubuntu-latest
    needs: recent-activity
    steps:
      - uses: lowlighter/metrics@v3.24
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Readme-Workflows
          repo: recent-activity
          template: markdown
          filename: README.md
          markdown: TEMPLATE.md
          markdown_cache: '.github/svg_cache'
          
          base: ""
          
          config_octicon: yes
          
          plugin_stargazers: yes
          plugin_contributors: yes
