name: Repo Generator

on:
   workflow_dispatch:
     inputs:
       Replace_Links_In_Markdown:
         description: 'Replace all matches from repo_config.json settings?'
         required: false
         default: 'true'

       Generate_Metrics_File:
        description: 'Generate a Metrics Image File?'
        required: false
        default: 'false'


jobs:
  test_job:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Updating links in README content
        if: ${{  github.event.inputs.Replace_Links_In_Markdown == 'true' }}
        run: |
          sudo apt-get install python3
          python3 .github/py_repo_tools/replace_repo_links.py
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Updated links in README content"
          git push
      - uses: lowlighter/metrics@v3.24    
      - name: Generating Metrics Image
      
        if: ${{  github.event.inputs.Generate_Metrics_File  == 'true' }}
        with:
          filename:  metrics.plugin.stargazers.svg
          plugin_stargazers_charts_type: chartist
          token: ${{ secrets.METRICS_TOKEN }}
          
 
          
          base: ""
          
          config_octicon: yes
          
          plugin_stargazers: yes
          plugin_contributors: yes
          # some logic to run if flag==true




 


