name: Replace README links

on: push


jobs:
  build:
    
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2


     # Setup Python
    - run: sudo apt-get install python3
    - uses: actions/checkout@v2
    - name: Replacing README links 
    # Run the Python Script
      run: python3 .github/py_repo_tools/replace_repo_links.py



    - name: Commit and Push Updated Content 
      run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git commit -m "Updated links in README content"
         git push
