name: Replace README links

on:
   workflow_dispatch:
     inputs:
       Files:
         description: 'URL(s) or File(s) to take screenshot of (seperate by comma):'
         required: true
         default: "https://github.com,"
       

       Directory_To_Get_HTML_File:
         description: 'The directory name to save screenshots to (example : path/to/directory'
         required: False
         default: 'false'

       Directory_To_Save_HTML_File:
        description: 'URL or File'
        required: True
        default: 'URL'


jobs:
  build:
    
    runs-on: ubuntu-latest

    steps: 
      - if: ${{ github.event.inputs.Directory_To_Get_HTML_File == 'true' }}
      - run: sudo apt-get install python3
      - uses: actions/checkout@v2
      - name: Replacing README links 
    # Run the Python Script
      - run: python3 .github/py_repo_tools/replace_repo_links.py
      - if: ${{ github.event.inputs.Directory_To_Get_HTML_File == 'false' }}
      - run: echo "hello"
 

      - name: Commit and Push Updated Content 
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git commit -m "Updated links in README content"
         git push
